#!/bin/bash
IMAGE_NAME=$DOCKER_USERNAME/$DOCKER_REPOSITORY:$DOCKER_TAG
CONTAINER_NAME=$DOCKER_REPOSITORY_$DOCKER_TAG

docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
docker pull $IMAGE_NAME
docker run -it --name $CONTAINER_NAME -d $IMAGE_NAME