#!/bin/bash
echo $DOCKER_USERNAME
echo $DOCKER_PASSWORD
echo $DOCKER_REPOSITORY
echo $DOCKER_TAG

docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
docker pull $DOCKER_USERNAME/$DOCKER_REPOSITORY:$DOCKER_TAG
CONTAINER_ID = $(docker run -it --name $DOCKER_REPOSITORY_$DOCKER_TAG -d $DOCKER_USERNAME/$DOCKER_REPOSITORY)
sleep 10
echo $(docker inspect -f {{.State.Running}} $CONTAINER_ID)