version: "3.9"

services:
  sso:
    container_name: sso
    image: ${DOCKER_USERNAME}/${DOCKER_REPOSITORY}:main
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - default

  postgres:
    container_name: postgres
    image: postgres:16-alpine
    volumes:
      - ./exports/postgres/data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: logity_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

networks:
  default:
    external: true
    name: existing-network